#!/usr/bin/env python3

print(1, "\t", format(1, 'o'), "\t", format(1,"X"), "\t", format(1,"b"))
print(2, "\t", format(2, 'o'), "\t", format(2,"X"), "\t", format(2,"b"))
print(3, "\t", format(3, 'o'), "\t", format(3,"X"), "\t", format(3,"b"))
print(4, "\t", format(4, 'o'), "\t", format(4,"X"), "\t", format(4,"b"))
print(5, "\t", format(5, 'o'), "\t", format(5,"X"), "\t", format(5,"b"))
print(6, "\t", format(6, 'o'), "\t", format(6,"X"), "\t", format(6,"b"))
print(7, "\t", format(7, 'o'), "\t", format(7,"X"), "\t", format(7,"b"))
print(8, "\t", format(8, 'o'), "\t", format(8,"X"), "\t", format(8,"b"))
print(9, "\t", format(9, 'o'), "\t", format(9,"X"), "\t", format(9,"b"))
print(10, "\t", format(10, 'o'), "\t", format(10,"X"), "\t", format(10,"b"))
print(11, "\t", format(11, 'o'), "\t", format(11,"X"), "\t", format(11,"b"))
print(12, "\t", format(12, 'o'), "\t", format(12,"X"), "\t", format(12,"b"))
print(13, "\t", format(13, 'o'), "\t", format(13,"X"), "\t", format(13,"b"))
print(14, "\t", format(14, 'o'), "\t", format(14,"X"), "\t", format(14,"b"))
print(15, "\t", format(15, 'o'), "\t", format(15,"X"), "\t", format(15,"b"))
print(16, "\t", format(16, 'o'), "\t", format(16,"X"), "\t", format(16,"b"))
print(17, "\t", format(17, 'o'), "\t", format(17,"X"), "\t", format(17,"b"))